apiVersion: v1
kind: Service
metadata:
  name: social-feed-kubernetes
spec:
  selector:
    app: social-feed-kubernetes
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      # nodePort: service-node-port-range
  type: LoadBalancer
