apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: social-feed-kubernetes
spec:
  replicas: 3
  selector:
    matchLabels:
      app: social-feed-kubernetes
  template:
    metadata:
      labels:
        app: social-feed-kubernetes
    spec:
      containers:
        - name: social-feed-kubernetes
          image: nginx:1.14.2
          ports:
            - containerPort: 80
